version: '3.8'

services:
  server:
    build: .
    container_name: chat-server
    command: ./server
    networks:
      chat-network:
        ipv4_address: 172.20.0.10
    ports:
      - "12345:12345"

  client1:
    build: .
    container_name: chat-client1
    command: sleep infinity
    networks:
      chat-network:
        ipv4_address: 172.20.0.11
    stdin_open: true
    tty: true

  client2:
    build: .
    container_name: chat-client2
    command: sleep infinity
    networks:
      chat-network:
        ipv4_address: 172.20.0.12
    stdin_open: true
    tty: true

networks:
  chat-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16